# NOTE: update this with your service name
service: zipservice

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-domain-manager
  - serverless-dotenv-plugin
custom:
  stage: ${opt:stage, self:provider.stage}
  dynamodb:
    stages:
        - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
    # migration:
    #   dir: offline/migrations
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001
    allowCache: true
  domains:
    prod: api.ekatvacollections.com
    staging: staging-api.ekatvacollections.com
    dev: dev-api.ekatvacollections.com
  customDomain:
    domainName: "${self:custom.domains.${self:custom.stage}}"
    basePath: shipping
    stage: "${self:custom.stage}"
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ["arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}", "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"]

    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: ["arn:aws:secretsmanager:ap-south-1:267910336395:secret:ekatva-delhivery-tokens-p8ch8y"]
functions:

  shippingdetails:
    handler: controllers/postofficeController.getPost
    events:
      - http:
          path: /postoffice
          method: get
          cors: true
          # authorizer: aws_iam
          query:
            pinCode: false
            state: false
            city: false

  addpostoffice:
    description: API to add India new post office details to DB 
    memorySize: 512 # memorySize for this specific function.
    handler: controllers/postofficeController.insertPostoffice
    events:
      - http:
          path: /postoffice
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:ap-south-1:267910336395:userpool/ap-south-1_5Gd00JfQ2

  shippingcharge:
    handler: controllers/postofficeController.getShippingcharges
    description: API integrated to live website to get the shipping charges and COD eligiblity
    memorySize: 1024 # memorySize for this specific function.
    events:
      - http:
          path: /charge
          method: post
          cors: true
          request: # configure method request and integration request settings
            schema: # Optional request schema validation; mapped by content type
              application/json: ${file(./schema/shipping.json)} # define the valid JSON Schema for a content-type
            passThrough: NEVER
          # authorizer: aws_iam
              
resources:
  Resources:
    customertable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: N
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        # ProvisionedThroughput:
        #       ReadCapacityUnits: 5
        #       WriteCapacityUnits: 5
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        # GlobalSecondaryIndexes:
        #   - IndexName: pinindex
        #     KeySchema:
        #     - AttributeName: Pincode
        #       KeyType: HASH
        #     - AttributeName: Postoffice
        #       KeyType: RANGE
        #     Projection:
        #       NonKeyAttributes:
        #         - StateName
        #         - District
        #         - Serviceable
        #         - Servicearea
        #         - Servicecode
        #         - Codeligible
        #         - Shippingrate
        #       ProjectionType: INCLUDE
        #     # ProvisionedThroughput:
        #     #   ReadCapacityUnits: 5
        #     #   WriteCapacityUnits: 5

